### ISSUE TITLE
move to JuliaStrings or JuliaText org?

### ISSUE THREAD

**Issue by StefanKarpinski** [simonster/NaturalSort.jl#4]
So that it can be actively maintained by others? @simonster, I've made you a member of JuliaStrings so you should just be able to transfer the repo. Then others can do things like [merge PRs](https://github.com/simonster/NaturalSort.jl/pull/3).

**Comment by StefanKarpinski** [comment]
I just realized there's the https://github.com/JuliaText org as well—I'm not sure which is more appropriate for this package. @aviks, @oxinabox, @mikeinnes, thoughts?

**Comment by MikeInnes** [comment]
Probably JuliaStrings as JuliaText is usually more high-level analysis, language etc. I don't have a particularly strong opinion about it myself though.

**Comment by StefanKarpinski** [comment]
Makes sense to me. Nothing else needs to be done then since I've added @simonster to JuliaStrings.

**Comment by simonster** [comment]
Would it still be useful to transfer this? If so, I'm happy to do so.

**Comment by simonster** [comment]
Done (and updated for Julia 1.0).
